### ISSUE TITLE
Playground improvements

### ISSUE THREAD

**Issue by lemmih** [rgeometry/rgeometry#32]
- [x] Export all drawing context functions.
 - [x] Export `fill_text/stroke_text` which takes the global transformation into account.
 - [x] `set_fill_style` should take a `&str` rather than `&JsValue`
 - [x] Rename `with_points` to `get_points`.
 - [ ] Add `set_default_points`.
 - [x] Set default font to `24px Menlo`.
 - [x] Set default `text_align` to `center`.
 - [x] Set default `text_baseline` to `middle`.
 - [x] Use `rgeometry_wasm::playground::*` by default?
 - [x] Use `rgeometry::{*, data::*}` by default?
 - [x] Set `(2,2)` as the default viewport.
 - [x] Deref `Cursor` to `Point`.

**Comment by Lemmih** [comment]
Create color palette:
 * Moveable points.
 * Non-moveable points.
 * Polygon area
 * Outlines (always be pure black?)
 * soft-success
 * soft-error
 * hard-error
